export const FETCH_FILMS_REQUEST = 'FETCH_FILMS_REQUEST';
export const FETCH_FILMS_SUCCESS = 'FETCH_FILMS_SUCCESS';
export const FETCH_FILMS_FAILURE = 'FETCH_FILMS_FAILURE';

export const SET_FILMS = 'SET_FILMS';
export const GET_FILMS = 'GET_FILMS';

export const SAVE_FILM = 'SAVE_FILM';
